# Generated by Django 5.0.6 on 2025-09-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
