# Generated by Django 5.0.6 on 2025-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextFinderApp', '0002_uploadedfiles_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='original_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='upload_type',
            field=models.CharField(blank=True, default='single', max_length=20, null=True),
        ),
    ]
