# Generated by Django 5.0.6 on 2025-10-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextFinderApp', '0003_uploadedfiles_original_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='original_path',
        ),
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='upload_type',
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='original_filename',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
